<?xml version="1.0"?>

<robot name="pantilt" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ubiquitous_display_description)/urdf/pantilt/pantilt.transmission.xacro"/>
  <xacro:include filename="$(find ubiquitous_display_description)/urdf/pantilt/pantilt.gazebo.xacro"/>


  <xacro:property name="base_to_box_height" value="0.066"/>
  <xacro:property name="box_to_proj_height" value="0.17"/>

  <material name="red" >
    <color rgba="0.7 0.0 0.7 1.0" />
  </material>
  <material name="blue" >
    <color rgba="0.0 0.7 0.7 1.0" />
  </material>
  <material name="green" >
    <color rgba="0.0 0.7 0.7 1.0" />
  </material>
  <material name="gray" >
    <color rgba="0.7 0.7 0.7 1.0" />
  </material>

  <xacro:macro name="pantilt_model" params="name parent">

    <link name="${name}base_link" >
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.07 0.085 0.065" /-->
          <mesh filename="package://ubiquitous_display_description/meshes/DAE/pantilt_base.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 ${base_to_box_height/2}" rpy="0 0 0"/>
       <mass value="0.78"/>
       <inertia
	    ixx="0.00190" ixy="0.0" ixz="0.0"
	    iyy="0.00202" iyz="0.0"
	    izz="0.00152"/>
     </inertial>
    </link>

    <link name="pan_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.35 0.095 0.003" /-->
          <mesh filename="package://ubiquitous_display_description/meshes/DAE/pan_link.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 0.0015" rpy="0 0 0"/>
       <mass value="1.5"/>
       <inertia
	    ixx="0.00150" ixy="0.0" ixz="0.0"
	    iyy="0.02191" iyz="0.0"
	    izz="0.02041"/>
     </inertial>
    </link>

    <link name="tilt_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.24 0.17 0.07" /-->
          <mesh filename="package://ubiquitous_display_description/meshes/DAE/tilt_link.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <mass value="1.3"/>
       <inertia
	    ixx="0.00536" ixy="0.0" ixz="0.0"
	    iyy="0.01441" iyz="0.0"
	    izz="0.01041"/>
     </inertial>
    </link>

    <link name="projector_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--box size="0.24 0.17 0.07" /-->
          <mesh filename="package://ubiquitous_display_description/meshes/DAE/projector.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>
     <inertial>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <mass value="2"/>
       <inertia
      ixx="0.00536" ixy="0.0" ixz="0.0"
      iyy="0.01441" iyz="0.0"
      izz="0.01041"/>
     </inertial>
    </link>

    <link name="projector_optical_frame"/>
    <link name="projector_gazebo_optical_frame"/>

    <joint name="${parent}_to_${name}base_link" type="fixed">
      <origin xyz="0 0 0.033 " rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="${name}base_link"/>
    </joint>

    <!--name of pan_joint and tilt_joint depend pantilt.yaml-->
    <joint name="pan_joint" type="revolute">
      <parent link="${name}base_link"/>
      <child link="pan_link"/>
      <origin xyz="0 0 ${base_to_box_height/2}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="-2.9670" upper="2.9670" effort="41" velocity="1"/>
      <!--<safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />-->
      <dynamics damping="0.7"/>
    </joint>

    <joint name="tilt_joint" type="revolute">
      <parent link="pan_link"/>
      <child link="tilt_link"/>
      <origin xyz="0.0905 0 0.170" rpy="0 -1.57 0" />
      <axis xyz="0 0 1" />
      <limit lower="-0.2617" upper="1.3" effort="10" velocity="1"/>
      <!--<safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />-->
      <dynamics damping="0.7"/>
    </joint>

    <joint name="tilt_link_to_projector_link" type="fixed">
      <origin xyz="0 0 0.093 " rpy="0 1.57 0" />
      <parent link="tilt_link"/>
      <child link="projector_link"/>
    </joint>
    <joint name="projector_link_to_projector_optical_frame" type="fixed">
      <origin xyz="0 0 0 " rpy="-1.57 0 0" />
      <parent link="projector_link"/>
      <child link="projector_optical_frame"/>
    </joint>
    <joint name="projector_link_to_projector_gazebo_optical_frame" type="fixed">
      <origin xyz="0 0 0 " rpy="1.57 0 0" />
      <parent link="projector_link"/>
      <child link="projector_gazebo_optical_frame"/>
    </joint>

  </xacro:macro>

</robot>
